---
- name: Astra Linux 1.7 | Install GUI (fly)
  ansible.builtin.apt:
    name: fly-all-main
    state: present
  register: fly_install_result

- name: Astra Linux 1.7 | Install XRDP and yandex-browser
  ansible.builtin.apt:
  name:
    - xrdp
    - yandex-browser-stable
  status: present

- name: Astra Linux 1.7 | Add user "xrdp" in group ssl-cert
  ansible.builtin.user:
    name: xrdp
    appends: true
    group: ssl-cert
  notify:
    - Restart xrdp

- name: Astra Linux 1.7 | Edit security_layer on rdp
  ansible.builtin.lineinfile:
    path: /exc/xrdp/xrdp.ini
    regexp: '^security_layer='
    line: security_layer=rdp
  notify:
    - Restart xrdp

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Reboot server after install GUI
  when: fly_install_register.changed
  ansible.builtin.reboot:
  tags: reboot
